Title and subtitle atoms adjustments
divriots/lcd pull request #106
Opened 2021-09-02 14:51 UTC by mveres

https://backlight.dev/edit/1SuMaEt5uxgp62VC8WVP/hero/src/index.vue?branch=atomic-design-web@tLlGPKdxk2VRYywCKUXNaV8PFt62

2021-09-02 15:49 UTC, gqio requested changes
I am very sorry but we can’t use title as className. It will leak in all class title we already have in the app. Please use another className

2021-09-02 15:50 UTC, gqio commented on title/src/title.css
> +  .title {
it’s not a title… It’a BigTitle if you want. but definitely not a title. I think it’s too generic title

2021-09-02 15:51 UTC, gqio commented on subtitle/src/subtitle.css
> -		text-base
Same I think it’s too generic subtitle. Please use something indicating it’s a big sub title

2021-09-03 11:47 UTC, mveres commented on title/src/title.css
> +  .title {
Ok, will do.
I checked where else `title` is used on the landing page and I thought we were safe... but indeed it's too generic.

2021-09-03 12:07 UTC, gqio approved these changes

2021-09-03 12:33 UTC, merged