Push from testimonial-revamp
divriots/lcd pull request #258
Opened 2022-03-14 10:52 UTC by charlene1804

2022-03-15 09:41 UTC, jorenbroekema requested changes
This looks great! Few small remarks. Glad these arrows are still useful :)

2022-03-15 09:41 UTC, jorenbroekema commented on studio.config.json
> +          "link",
Is this one intended? I don't see a link atom package in backlight

2022-03-15 09:41 UTC, jorenbroekema commented on testimonial-card/src/index.tsx
> +            fill="#f8c307"
We should probably use CSS custom property here e.g. --rev-colors-accent-base or something, I believe this is our main brand color yellow right?

2022-03-15 09:41 UTC, jorenbroekema commented on testimonial/src/index.tsx
> +            className={`flex items-center max-w-full overflow-x-scroll ml-4 ${
![image](https://user-images.githubusercontent.com/36734656/158346768-2cdd6b5e-33f7-4b15-87a6-ed4bb40cc3b3.png)
The margin-left `ml-4` seems weird to me because this cuts the container differently on the left vs on the right

2022-03-15 09:41 UTC, jorenbroekema commented on testimonial-card/src/index.tsx
> +    <div className="bg-gray-darker font-light text-lg text-white rounded-lg px-4 lg:px-8 py-5 flex flex-col lg:flex-row my-6 w-64 lg:w-96">
I think we need some box-shadow as well here if I look at the design

2022-03-15 09:41 UTC, jorenbroekema commented on testimonial/src/index.tsx
> +          <div className="relative z-10 pt-16 sm:w-96 text-center">
`sm:w-96` can be removed. In the design, this text is on 1 line for desktop. for smaller viewports the text will wrap on its own.

![image](https://user-images.githubusercontent.com/36734656/158347643-292a4253-5682-48cc-852c-92f5fb70c3bc.png)

We should give it a bit of padding though so it doesn't hit the edge of the screen on smaller viewports.

2022-03-15 09:41 UTC, jorenbroekema commented on testimonial/src/index.tsx
>            <svg
These need some box-shadow as well if I look at the design

2022-03-15 09:45 UTC, charlene1804 commented on studio.config.json
> +          "link",
No you're right that should be gone.

2022-03-15 09:46 UTC, charlene1804 commented on testimonial-card/src/index.tsx
> +            fill="#f8c307"
Yep, will fix that too.

2022-03-15 09:47 UTC, charlene1804 commented on testimonial/src/index.tsx
> +            className={`flex items-center max-w-full overflow-x-scroll ml-4 ${
May be worth discussing with Thais or Ardena

2022-03-15 10:29 UTC, ardena-riots reviewed
As already shared on discord and BKL, main thing to change design-wise: 
- Testimonials title should be on one line (@jorenbroekema already identified this)

2022-03-15 10:33 UTC, charlene1804 commented on testimonial-card/src/index.tsx
> +            fill="#f8c307"
I can't seem to be able to do that there.

2022-03-15 10:39 UTC, jorenbroekema commented on testimonial-card/src/index.tsx
> +            fill="#f8c307"
`style="fill: var(--rev-colors-accent-base"` probably works?

2022-03-15 10:41 UTC, charlene1804 commented on testimonial-card/src/index.tsx
> +    <div className="bg-gray-darker font-light text-lg text-white rounded-lg px-4 lg:px-8 py-5 flex flex-col lg:flex-row my-6 w-64 lg:w-96">
You're right I missed that.

2022-03-15 18:35 UTC, charlene1804 commented on testimonial-card/src/index.tsx
> +            fill="#f8c307"
I can use color variables in class="" but not in fill="", which is why I copy pasted it.

2022-03-18 17:41 UTC, charlene1804 commented on testimonial/src/index.tsx
> +            className={`flex items-center max-w-full overflow-x-scroll ml-4 ${
Fixed

2022-03-19 12:37 UTC, gqio approved these changes

2022-03-21 09:52 UTC, jorenbroekema commented on testimonial/src/index.tsx
> +            viewBox="0 0 20 20"
I don't think the viewBox is supposed to change here, it's directly coupled to the `d` attribute in the path element, it acts as a bounding box for the drawn SVG paths. Width/height then scales the whole thing

2022-03-21 09:52 UTC, jorenbroekema commented on testimonial/src/index.tsx
> +            viewBox="0 0 20 20"
Same here

2022-03-21 09:56 UTC, charlene1804 commented on testimonial/src/index.tsx
> +            viewBox="0 0 20 20"
Hmm from what I remember the alignement of the arrow inside the circle was weird unless I changed the viewbox values as well.

2022-03-21 10:32 UTC, jorenbroekema approved these changes

2022-03-21 10:33 UTC, merged

2022-03-21 10:33 UTC, jorenbroekema commented
@gqio ??

2022-03-21 10:37 UTC, gqio commented
> @gqio ??

How I can help here ?

2022-03-21 10:45 UTC, jorenbroekema commented
It wasn't showing in the GitHub UI for me where your "no rem" comment was referencing to 😓

2022-03-21 11:20 UTC, charlene1804 commented
@jorenbroekema Thais confirmed she wanted rem, we're all good.